name: Terraform Code Testing

on:
  pull_request:
    branches:
      - master 
  workflow_dispatch:

jobs:
  terraform-test:
    name: Test Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4 

      - name: Install Terraform provider dependencies
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Run Terraform fmt check
        run: terraform fmt -check -diff -recursive